gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
  authorColors:
    'Nguyen Minh Dan': '#03bafc'
git:
  paging:
    colorArg: always
    pager: delta --paging never --dark --true-color never
    # pager: diff-so-fancy
os:
  edit: 'lvim {{filename}}'
  editAtLine: 'lvim --line={{line}} {{filename}}'
  editAtLineAndWait: 'lvim --block --line={{line}} {{filename}}'
  editInTerminal: true
