gui:
  showIcons: true
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
git:
  paging:
    colorArg: always
    pager: delta --paging never --dark --true-color never
    # pager: diff-so-fancy
