[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#434758"
blue = "#9cc4ff"
cyan = "#a3f7ff"
green = "#ddffa7"
magenta = "#e1acff"
red = "#ff8b92"
white = "#ffffff"
yellow = "#ffe585"

[colors.normal]
black = "#101010"
blue = "#82aaff"
cyan = "#89ddff"
green = "#c3e88d"
magenta = "#c792ea"
red = "#f07178"
white = "#d0d0d0"
yellow = "#ffcb6b"

[colors.primary]
background = "#1a1a1a"
foreground = "#ffffff"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 9.0

[font.bold]
family = "mononoki Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "mononoki Nerd Font Mono"
style = "BoldItalic"

[font.normal]
family = "mononoki Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 1
y = 1
